import { defineConfig } from "tsup";

export default defineConfig([
  {
    dts: true,
    entry: ["src/core/app"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/app",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/auth"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/auth",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/settings"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/settings",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/file-system/index.ts"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/file-system",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/file-system/mapper.ts"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/file-system",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/receiver"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/receiver",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/commerce/index.ts"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/commerce",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/commerce/cart.ts"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/commerce",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/commerce/order.ts"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/commerce",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
  {
    dts: true,
    entry: ["src/core/locations"],
    format: ["esm", "cjs"],
    minify: true,
    target: "esnext",
    outDir: "dist/locations",
    splitting: true,
    external: [],
    tsconfig: "./tsconfig.json",
    bundle: true,
    cjsInterop: true,
    clean: true,
    noExternal: [/.*/],
    treeshake: true,
  },
]);
