name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Set up environment variables
        run: |
          echo "KANVAS_URL=${{ secrets.KANVAS_URL }}" >> $GITHUB_ENV
          echo "KANVAS_KEY=${{ secrets.KANVAS_APP_KEY }}" >> $GITHUB_ENV
          echo "KANVAS_USER=${{ secrets.KANVAS_TEST_USER }}" >> $GITHUB_ENV
          echo "KANVAS_PASSWORD=${{ secrets.KANVAS_TEST_PASSWORD }}" >> $GITHUB_ENV

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: 'install'

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build