name: CI
on: [push]
jobs:
  build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["21.x"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: pnpm/action-setup@v4
        with:
          cmd: "install"

      - name: Build
        run: pnpm run build
