name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      # CHANGE: Also upload the lockfile to ensure consistent dependencies in the next job.
      - uses: actions/upload-artifact@v4
        with:
          name: package-artifact
          path: |
            dist/
            package.json
            pnpm-lock.yaml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      # ADDED: Install dependencies using the lockfile from the build job.
      # This makes commands like 'tsup' available to the 'prepare' script that runs before publishing.
      - run: pnpm install --frozen-lockfile

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
